require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
