name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        ruby: [ '2.7', '3.0', '3.1', '3.2' ]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop -f github

      - name: Run tests
        run: bundle exec rake test
